-- lua/snippets/emoji.lua
-- Emoji snippets with Slack-style :emoji: syntax
-- Works with LuaSnip and blink.cmp
--
-- Usage: Type :smile: then trigger completion (Tab or Ctrl-Space)

local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

-- Add emoji snippets to all file types
ls.add_snippets("all", {
  -- ==================== Smileys & Emotion ====================
  s(":smile:", t("😄")),
  s(":grin:", t("😁")),
  s(":joy:", t("😂")),
  s(":rofl:", t("🤣")),
  s(":laughing:", t("😆")),
  s(":sweat_smile:", t("😅")),
  s(":wink:", t("😉")),
  s(":blush:", t("😊")),
  s(":innocent:", t("😇")),
  s(":heart_eyes:", t("😍")),
  s(":star_struck:", t("🤩")),
  s(":kissing_heart:", t("😘")),
  s(":thinking:", t("🤔")),
  s(":neutral:", t("😐")),
  s(":expressionless:", t("😑")),
  s(":confused:", t("😕")),
  s(":worried:", t("😟")),
  s(":slightly_frowning:", t("🙁")),
  s(":frowning:", t("☹️")),
  s(":cry:", t("😢")),
  s(":sob:", t("😭")),
  s(":scream:", t("😱")),
  s(":disappointed:", t("😞")),
  s(":tired:", t("😫")),
  s(":angry:", t("😠")),
  s(":rage:", t("😡")),
  s(":triumph:", t("😤")),
  s(":relieved:", t("😌")),
  s(":pensive:", t("😔")),
  s(":sleepy:", t("😪")),
  s(":sleeping:", t("😴")),
  s(":dizzy:", t("😵")),
  s(":sunglasses:", t("😎")),
  s(":nerd:", t("🤓")),
  s(":monocle:", t("🧐")),
  s(":exploding_head:", t("🤯")),
  s(":eyes:", t("👀")),
  s(":raised_eyebrow:", t("🤨")),
  s(":upside_down:", t("🙃")),
  s(":shrug:", t("🤷")),
  s(":facepalm:", t("🤦")),

  -- ==================== Hand Gestures ====================
  s(":wave:", t("👋")),
  s(":raised_hand:", t("✋")),
  s(":ok_hand:", t("👌")),
  s(":thumbsup:", t("👍")),
  s(":thumbsdown:", t("👎")),
  s(":fist:", t("✊")),
  s(":punch:", t("👊")),
  s(":clap:", t("👏")),
  s(":hands:", t("🙌")),
  s(":pray:", t("🙏")),
  s(":muscle:", t("💪")),
  s(":point_up:", t("☝️")),
  s(":point_down:", t("👇")),
  s(":point_left:", t("👈")),
  s(":point_right:", t("👉")),
  s(":v:", t("✌️")),
  s(":crossed_fingers:", t("🤞")),
  s(":metal:", t("🤘")),
  s(":call_me:", t("🤙")),

  -- ==================== Hearts & Love ====================
  s(":heart:", t("❤️")),
  s(":orange_heart:", t("🧡")),
  s(":yellow_heart:", t("💛")),
  s(":green_heart:", t("💚")),
  s(":blue_heart:", t("💙")),
  s(":purple_heart:", t("💜")),
  s(":black_heart:", t("🖤")),
  s(":white_heart:", t("🤍")),
  s(":broken_heart:", t("💔")),
  s(":sparkling_heart:", t("💖")),
  s(":two_hearts:", t("💕")),
  s(":heartbeat:", t("💓")),

  -- ==================== Celebrations ====================
  s(":tada:", t("🎉")),
  s(":confetti:", t("🎊")),
  s(":balloon:", t("🎈")),
  s(":party:", t("🥳")),
  s(":sparkles:", t("✨")),
  s(":star:", t("⭐")),
  s(":star2:", t("🌟")),
  s(":fireworks:", t("🎆")),
  s(":sparkler:", t("🎇")),

  -- ==================== Symbols & Indicators ====================
  s(":check:", t("✓")),
  s(":x:", t("✗")),
  s(":checkmark:", t("✅")),
  s(":cross_mark:", t("❌")),
  s(":warning:", t("⚠️")),
  s(":no_entry:", t("⛔")),
  s(":exclamation:", t("❗")),
  s(":question:", t("❓")),
  s(":bangbang:", t("‼️")),
  s(":interrobang:", t("⁉️")),
  s(":double_exclamation:", t("‼️")),
  s(":info:", t("ℹ️")),
  s(":recycle:", t("♻️")),
  s(":copyright:", t("©️")),
  s(":registered:", t("®️")),
  s(":tm:", t("™️")),

  -- ==================== Arrows ====================
  s(":arrow_up:", t("⬆️")),
  s(":arrow_down:", t("⬇️")),
  s(":arrow_left:", t("⬅️")),
  s(":arrow_right:", t("➡️")),
  s(":arrow_upper_right:", t("↗️")),
  s(":arrow_lower_right:", t("↘️")),
  s(":arrow_lower_left:", t("↙️")),
  s(":arrow_upper_left:", t("↖️")),
  s(":arrow_heading_up:", t("⤴️")),
  s(":arrow_heading_down:", t("⤵️")),
  s(":leftright:", t("↔️")),
  s(":updown:", t("↕️")),

  -- ==================== Tech & Work ====================
  s(":computer:", t("💻")),
  s(":keyboard:", t("⌨️")),
  s(":mouse:", t("🖱️")),
  s(":desktop:", t("🖥️")),
  s(":laptop:", t("💾")),
  s(":phone:", t("📱")),
  s(":email:", t("📧")),
  s(":envelope:", t("✉️")),
  s(":inbox:", t("📥")),
  s(":outbox:", t("📤")),
  s(":package:", t("📦")),
  s(":briefcase:", t("💼")),
  s(":file:", t("📄")),
  s(":folder:", t("📁")),
  s(":open_folder:", t("📂")),
  s(":clipboard:", t("📋")),
  s(":calendar:", t("📅")),
  s(":chart:", t("📊")),
  s(":bar_chart:", t("📊")),
  s(":chart_increasing:", t("📈")),
  s(":chart_decreasing:", t("📉")),
  s(":page_facing_up:", t("📃")),
  s(":memo:", t("📝")),
  s(":pencil:", t("✏️")),
  s(":lock:", t("🔒")),
  s(":unlock:", t("🔓")),
  s(":key:", t("🔑")),
  s(":hammer:", t("🔨")),
  s(":wrench:", t("🔧")),
  s(":gear:", t("⚙️")),
  s(":link:", t("🔗")),
  s(":chains:", t("⛓️")),
  s(":magnet:", t("🧲")),
  s(":bug:", t("🐛")),
  s(":microscope:", t("🔬")),
  s(":telescope:", t("🔭")),

  -- ==================== Nature & Animals ====================
  s(":fire:", t("🔥")),
  s(":zap:", t("⚡")),
  s(":boom:", t("💥")),
  s(":collision:", t("💥")),
  s(":sunny:", t("☀️")),
  s(":cloud:", t("☁️")),
  s(":rain:", t("🌧️")),
  s(":snowflake:", t("❄️")),
  s(":wind:", t("💨")),
  s(":tornado:", t("🌪️")),
  s(":rainbow:", t("🌈")),
  s(":star:", t("⭐")),
  s(":moon:", t("🌙")),
  s(":earth:", t("🌍")),
  s(":plant:", t("🌱")),
  s(":seedling:", t("🌱")),
  s(":tree:", t("🌳")),
  s(":evergreen:", t("🌲")),
  s(":cactus:", t("🌵")),
  s(":four_leaf_clover:", t("🍀")),
  s(":dog:", t("🐕")),
  s(":cat:", t("🐈")),
  s(":mouse:", t("🐁")),
  s(":rabbit:", t("🐰")),
  s(":fox:", t("🦊")),
  s(":bear:", t("🐻")),
  s(":panda:", t("🐼")),
  s(":koala:", t("🐨")),
  s(":tiger:", t("🐯")),
  s(":lion:", t("🦁")),
  s(":cow:", t("🐮")),
  s(":pig:", t("🐷")),
  s(":frog:", t("🐸")),
  s(":monkey:", t("🐵")),
  s(":chicken:", t("🐔")),
  s(":penguin:", t("🐧")),
  s(":bird:", t("🐦")),
  s(":baby_chick:", t("🐤")),
  s(":bee:", t("🐝")),
  s(":butterfly:", t("🦋")),
  s(":snail:", t("🐌")),
  s(":turtle:", t("🐢")),
  s(":snake:", t("🐍")),
  s(":dragon:", t("🐉")),
  s(":whale:", t("🐋")),
  s(":dolphin:", t("🐬")),
  s(":fish:", t("🐟")),
  s(":octopus:", t("🐙")),

  -- ==================== Food & Drink ====================
  s(":coffee:", t("☕")),
  s(":tea:", t("🍵")),
  s(":beer:", t("🍺")),
  s(":wine:", t("🍷")),
  s(":cocktail:", t("🍸")),
  s(":pizza:", t("🍕")),
  s(":hamburger:", t("🍔")),
  s(":fries:", t("🍟")),
  s(":popcorn:", t("🍿")),
  s(":hotdog:", t("🌭")),
  s(":taco:", t("🌮")),
  s(":burrito:", t("🌯")),
  s(":sushi:", t("🍣")),
  s(":ramen:", t("🍜")),
  s(":curry:", t("🍛")),
  s(":rice:", t("🍚")),
  s(":bread:", t("🍞")),
  s(":egg:", t("🥚")),
  s(":cheese:", t("🧀")),
  s(":apple:", t("🍎")),
  s(":orange:", t("🍊")),
  s(":banana:", t("🍌")),
  s(":watermelon:", t("🍉")),
  s(":grapes:", t("🍇")),
  s(":strawberry:", t("🍓")),
  s(":peach:", t("🍑")),
  s(":cherries:", t("🍒")),
  s(":pineapple:", t("🍍")),
  s(":avocado:", t("🥑")),
  s(":tomato:", t("🍅")),
  s(":carrot:", t("🥕")),
  s(":corn:", t("🌽")),
  s(":cookie:", t("🍪")),
  s(":cake:", t("🍰")),
  s(":birthday:", t("🎂")),
  s(":cupcake:", t("🧁")),
  s(":donut:", t("🍩")),
  s(":icecream:", t("🍦")),
  s(":candy:", t("🍬")),
  s(":chocolate:", t("🍫")),
  s(":honey:", t("🍯")),

  -- ==================== Travel & Places ====================
  s(":rocket:", t("🚀")),
  s(":airplane:", t("✈️")),
  s(":car:", t("🚗")),
  s(":taxi:", t("🚕")),
  s(":bus:", t("🚌")),
  s(":train:", t("🚆")),
  s(":ship:", t("🚢")),
  s(":bike:", t("🚲")),
  s(":scooter:", t("🛴")),
  s(":skateboard:", t("🛹")),
  s(":helicopter:", t("🚁")),
  s(":satellite:", t("🛰️")),
  s(":house:", t("🏠")),
  s(":building:", t("🏢")),
  s(":office:", t("🏢")),
  s(":hospital:", t("🏥")),
  s(":school:", t("🏫")),
  s(":hotel:", t("🏨")),
  s(":bank:", t("🏦")),
  s(":tent:", t("⛺")),
  s(":mountain:", t("⛰️")),
  s(":beach:", t("🏖️")),
  s(":island:", t("🏝️")),
  s(":camping:", t("🏕️")),

  -- ==================== Activities & Sports ====================
  s(":soccer:", t("⚽")),
  s(":basketball:", t("🏀")),
  s(":football:", t("🏈")),
  s(":baseball:", t("⚾")),
  s(":tennis:", t("🎾")),
  s(":volleyball:", t("🏐")),
  s(":8ball:", t("🎱")),
  s(":golf:", t("⛳")),
  s(":trophy:", t("🏆")),
  s(":medal:", t("🏅")),
  s(":dart:", t("🎯")),
  s(":game:", t("🎮")),
  s(":dice:", t("🎲")),
  s(":chess:", t("♟️")),
  s(":art:", t("🎨")),
  s(":musical_note:", t("🎵")),
  s(":notes:", t("🎶")),
  s(":guitar:", t("🎸")),
  s(":microphone:", t("🎤")),
  s(":headphones:", t("🎧")),
  s(":camera:", t("📷")),
  s(":video_camera:", t("📹")),
  s(":clapper:", t("🎬")),
  s(":movie:", t("🎥")),

  -- ==================== Objects ====================
  s(":watch:", t("⌚")),
  s(":alarm_clock:", t("⏰")),
  s(":stopwatch:", t("⏱️")),
  s(":hourglass:", t("⌛")),
  s(":battery:", t("🔋")),
  s(":plug:", t("🔌")),
  s(":bulb:", t("💡")),
  s(":flashlight:", t("🔦")),
  s(":candle:", t("🕯️")),
  s(":gift:", t("🎁")),
  s(":balloon:", t("🎈")),
  s(":money:", t("💰")),
  s(":dollar:", t("💵")),
  s(":credit_card:", t("💳")),
  s(":gem:", t("💎")),
  s(":crystal_ball:", t("🔮")),
  s(":hocho:", t("🔪")),
  s(":bomb:", t("💣")),
  s(":pill:", t("💊")),
  s(":syringe:", t("💉")),
  s(":smoking:", t("🚬")),

  -- ==================== Flags (common ones) ====================
  s(":flag_us:", t("🇺🇸")),
  s(":flag_gb:", t("🇬🇧")),
  s(":flag_ca:", t("🇨🇦")),
  s(":flag_au:", t("🇦🇺")),
  s(":flag_de:", t("🇩🇪")),
  s(":flag_fr:", t("🇫🇷")),
  s(":flag_es:", t("🇪🇸")),
  s(":flag_it:", t("🇮🇹")),
  s(":flag_jp:", t("🇯🇵")),
  s(":flag_kr:", t("🇰🇷")),
  s(":flag_cn:", t("🇨🇳")),
  s(":flag_in:", t("🇮🇳")),
  s(":flag_br:", t("🇧🇷")),
  s(":flag_mx:", t("🇲🇽")),

  -- ==================== Math & Logic ====================
  s(":plus:", t("➕")),
  s(":minus:", t("➖")),
  s(":multiply:", t("✖️")),
  s(":divide:", t("➗")),
  s(":infinity:", t("∞")),
  s(":percent:", t("%")),
  s(":degree:", t("°")),
  s(":pi:", t("π")),
  s(":alpha:", t("α")),
  s(":beta:", t("β")),
  s(":gamma:", t("γ")),
  s(":delta:", t("Δ")),
  s(":lambda:", t("λ")),
  s(":sigma:", t("Σ")),
  s(":theta:", t("θ")),
  s(":omega:", t("Ω")),
  s(":approximately:", t("≈")),
  s(":not_equal:", t("≠")),
  s(":less_equal:", t("≤")),
  s(":greater_equal:", t("≥")),
  s(":much_less:", t("≪")),
  s(":much_greater:", t("≫")),

  -- ==================== Zodiac ====================
  s(":aries:", t("♈")),
  s(":taurus:", t("♉")),
  s(":gemini:", t("♊")),
  s(":cancer:", t("♋")),
  s(":leo:", t("♌")),
  s(":virgo:", t("♍")),
  s(":libra:", t("♎")),
  s(":scorpio:", t("♏")),
  s(":sagittarius:", t("♐")),
  s(":capricorn:", t("♑")),
  s(":aquarius:", t("♒")),
  s(":pisces:", t("♓")),
})

-- The line beneath this is called `modeline`. See `:help modeline`
-- vim: ts=2 sts=2 sw=2 et
